config/routes.rb
Rails.application.routes.draw do
    resources :tweets
    root 'tweets#index'
    get 'get_tweet/:id', to: 'tweet#get_tweet'
    
    resources :users
    get 'get_user/:id', to: 'user#get_user'
    get 'top/main'
    post 'top/login'
    get 'top/logout'
    
    resources :likes
    post 'likes/index'
    get 'likes/index'
    
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :tweet
end

app/models/top.rb
class Top < ApplicationRecord
    
end

app/models/tweet.rb
class Tweet < ApplicationRecord
has_many :likes
has_many :like_user, through: :likes, source: :user
end

app/models/user.rb
class User < ApplicationRecord
    has_many :likes #多:多
    has_many :like_tweets, through: :likes, source: :tweet #多:多
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        @tweet = Tweet.find(params[:tweet_id])
        @user = User.find_by(uid: session[:login_uid])
        @user.like_tweets << @tweet
        redirect_to root_path
    end
    
    def destroy
        @tweet = Tweet.find(params[:id])
        @user = User.find_by(uid: session[:login_uid])
        @tweet.likes.find_by(user_id: @user.id).destroy
        redirect_to root_path
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
    def main
        render 'login'
    end
    def login
        if BCrypt::Password.new($login_password) == params[:pass]
        #if User.find_by(uid: params[:uid],pass: params[:pass])
            session[:login_uid] = params[:uid]
            redirect_to root_path
        else
            render 'error'
        end
    end
    def logout
        session.delete(:login_uid)
        redirect_to root_path
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    def index
        @tweet = Tweet.all
    end
    
    def new
        @tweet = Tweet.new
    end
    
    def create
        @tweet =Tweet.new(message: params[:tweet][:message])
        if @tweet.save
            flash[:notice] = 'ツイート完了'
            redirect_to tweets_path
        else 
            render new_tweet_path
        end
    end
    
    def destroy
        tweet = Tweet.find(params[:id])
        tweet.destroy
        redirect_to tweets_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @user = User.all
    end
    
    def new
        @user = User.new
    end
    
    def create
        uid = params[:user][:uid]
        pass = params[:user][:pass]
        $login_password = BCrypt::Password.create(pass)
        @user =User.new(uid: uid,pass: $login_password)
        
        if @user.save
            flash[:notice] = 'ユーザ登録完了'
            redirect_to users_path
        else 
            render new_user_path
        end
    end
    
    def destroy
        user = User.find(params[:id])
        user.destroy
        redirect_to users_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/top/error.html.erb
ログイン失敗！
<%= link_to '戻る' , :back %>

app/views/top/login.html.erb
<%= form_tag '/top/login', method: :post do %>
    <%= label_tag :uid, 'uid' %>
    <%= text_field_tag :uid %>
    <%= label_tag :pass, 'pass' %>
    <%= password_field_tag :pass %>
    <%= submit_tag 'ログイン' %>
<% end %>
<%= link_to 'ユーザ一覧','/users/' %>
<p><%= link_to 'メイン', root_path %></p>

app/views/top/main.html.erb
<%= link_to 'ユーザ一覧','/users' %><br>
<%= link_to 'ログアウト',top_logout_path %>

app/views/tweets/index.html.erb
<% if flash[:notice] %>
    <%= flash[:notice] %>
<% end %>

<% @tweet.each do |tweet| %>
<p><%= tweet.message %>
<% if session[:login_uid] %>
<%= link_to '削除', "/tweets/#{tweet.id}",method: :delete %>
<%= link_to 'いいね', likes_path(tweet_id: tweet.id), method: :post %>
<%= link_to 'いいね削除', like_path(tweet), method: :delete %>
</p><% end %>
<% end %>

<% if session[:login_uid] %>
    <p><%= link_to 'ツイートする', '/tweets/new' %>：
    <%= link_to 'ログアウト',top_logout_path %>：
    <%= link_to 'ユーザ一覧','/users/' %></p>
<% else %>
    <p><%= link_to 'ログイン', '/top/main' %></p>
<% end %>

app/views/tweets/new.html.erb
<% if @tweet.errors.present? %>
<ul>
<% @tweet.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
<% end %>

<%= form_for @tweet , url: {action: :create} do |f| %>
<p><%= f.label :message, 'メッセージを入力してください。' %></p>
<%= f.text_field :message %>

<%= f.submit 'つぶやく' %>
<% end %>

app/views/users/index.html.erb
<% if flash[:notice] %>
    <%= flash[:notice] %>
<% end %>

<% @user.each do |user| %> 
<p>
uid:<%= user.uid %>　pass:<%= user.pass %>
<%= link_to '削除', "/users/#{user.id}",method: :delete %>
</p>
<% end %>
<p><%= link_to 'ユーザ登録', '/users/new' %></p>
<p><%= link_to 'メイン', '/' %></p>

app/views/users/new.html.erb
<% if @user.errors.present? %>
<ul>
<% @user.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
<% end %>

<%= form_for @user , url: {action: :create} do |f| %>
<p><%= f.label :uid, 'uid' %>
<%= f.text_field :uid %>

<%= f.label :pass, 'pass' %>
<%= f.text_field :pass %>

<%= f.submit '登録' %></p>
<% end %>